### PR TITLE
Add playlist support

### PR DESCRIPTION
**Pull request by metalstrolch**

### CODE REVIEW

**Comment by DanielGibson** [comment]
?

**Comment by metalstrolch** [comment]
Sorry for the hassle. Should have gone to my fork instead.
But if you interested in the playlist support I did there, I could provide you with a pull request without commit 91f3942. This then will keep your build system intact.

**Comment by DanielGibson** [comment]
thanks for the offer, but I handle playlists outside of libwrclient and just pass the URL to the stream to it (seemed cleaner that way, fewer different states in libwrclient; I could imagine an additional function that gets a playlist URL and returns the stream URL to feed into `WRC_CreateStream()` though)

That the race condition mentioned in https://github.com/MasterbrainBytes/libwrclient/pull/1/commits/85b40d11ebc71baf4520a4c4f07b2c03529e2303 - does it only affect your fork (due to playlist handling) or do you think it could also happen in the original code?

**Comment by DanielGibson** [comment]
By the way, I'm glad to see someone found this code useful :-)

**Comment by metalstrolch** [comment]
The race condition can happen in your code as well. This won't crash, but may cause a WRC_StopStreaming call to be ignored. Why:

If one thread is running WRC_StartStreaming (and therefore curl) and another thread tries to stop it, then the stop can fail if the other thread is processing the curlWriteFun in a path that ends in changing streamState. Then curlWriteFun overwrites streamState again ignoring the stop.

Using a dedicated flag for stopping prevents this, as curlWriteFun will never write it.

BTW: I plan to embed this into my private curses based media player at home replacing a solution calling mplayer in the background. So I don't have playlist support somewhere else. That's why i added it. Additionally I have no clue how you're building it and why you carry that much binaries. That's why I throwed that away replacing it by cmake build script. Nice (and small) solution without much dependencies.

**Pull request closed without merging**
